Import('RTT_ROOT')
Import('rtconfig')
from building import *

src = Glob('*.c')
cwd = GetCurrentDir()
CPPPATH = [cwd]
libs  = ['voicechanger_gcc']
libpath  = [cwd]


#group = DefineGroup('voicechanger', src, depend = [''], CPPPATH = CPPPATH)
group = DefineGroup('voice_changer', src, depend = [''], LIBS = libs, LIBPATH = libpath, CPPPATH = CPPPATH)


Return('group')
