@echo off
@REM generate_sys_config alias_project_name targe_sys_config
@REM example: 
@REM generate_sys_config bk7231u config\sys_config.h

if "%2" equ "" (
set old_sys_config=config\sys_config.h
set old_rtconfig=rtconfig.h
)

if not exist config (
	mkdir config
)

if "%1" equ "bk7231u" (
set new_sys_config=beken378\app\config\sys_config_bk7231u.h
set new_linkscript=config\bk72xx.lds
set new_rt_config=config\rtconfig\rtconfig_bk7231u.h
goto update_sys_config
)
if "%1" equ "bk7231n" (
set new_sys_config=beken378\app\config\sys_config_bk7231n.h
set new_linkscript=config\bk7231n_boot.lds
set new_rt_config=config\rtconfig\rtconfig_bk7231n.h
goto update_sys_config
)
if "%1" equ "bk7251" (
set new_sys_config=beken378\app\config\sys_config_bk7251.h
set new_linkscript=config\bk72xx.lds
set new_rt_config=config\rtconfig\rtconfig_bk7251.h
goto update_sys_config
)
if "%1" equ "bk7238" (
set new_sys_config=beken378\app\config\sys_config_bk7238.h
set new_linkscript=config\bk7238_boot.lds
set new_rt_config=config\rtconfig\rtconfig_bk7238.h
goto update_sys_config
)
if "%1" equ "bk7252n" (
set new_sys_config=beken378\app\config\sys_config_bk7252n.h
set new_linkscript=config\bk7252n_boot.lds
set new_rt_config=config\rtconfig\rtconfig_bk7252n.h
goto update_sys_config
)
if "%1" equ "bk7231" (
set new_sys_config=beken378\app\config\sys_config_bk7231.h
set new_linkscript=config\bk72xx.lds
set new_rt_config=config\rtconfig\rtconfig_bk7231.h
goto update_sys_config
)
if "%1" equ "bk7271" (
set new_sys_config=beken378\app\config\sys_config_bk7271.h
set new_linkscript=config\bk72xx.lds
set new_rt_config=config\rtconfig\rtconfig_bk7271.h
goto update_sys_config
)
if "%1" equ "" (
set new_sys_config=beken378\app\config\sys_config_bk7231u.h
set new_linkscript=config\bk72xx.lds
set new_rt_config=config\rtconfig\rtconfig_bk7231u.h
goto update_sys_config
)

set new_sys_config=beken378\app\config\%1.h
set new_linkscript=config\bk72xx.lds


:update_sys_config

set new_hash=
set old_hash=

setlocal enabledelayedexpansion

if exist %new_sys_config% (
	for /f "eol=C skip=1 tokens=*" %%i in ('certutil -hashfile %new_sys_config% MD5') do set new_hash=!new_hash!%%i
	set new_hash=!new_hash: =!
	echo hash^(%new_sys_config%^)=!new_hash!
) else (
    echo %new_sys_config% not exist!
	goto :EOF
)
if exist %old_sys_config% (
	for /f "eol=C skip=1 tokens=*" %%i in ('certutil -hashfile %old_sys_config% MD5') do set old_hash=!old_hash!%%i
	set old_hash=!old_hash: =!
	echo hash^(%old_sys_config%^)=!old_hash!
)

if !new_hash! neq !old_hash! (
	copy %new_sys_config% %old_sys_config% /Y
)

set new_hash=
set old_hash=

setlocal enabledelayedexpansion

if exist %new_rt_config% (
	for /f "eol=C skip=1 tokens=*" %%i in ('certutil -hashfile %new_rt_config% MD5') do set new_hash=!new_hash!%%i
	set new_hash=!new_hash: =!
	echo hash^(%new_rt_config%^)=!new_hash!
) else (
    echo %new_rt_config% not exist!
	goto :EOF
)
if exist %old_rtconfig% (
	for /f "eol=C skip=1 tokens=*" %%i in ('certutil -hashfile %old_rtconfig% MD5') do set old_hash=!old_hash!%%i
	set old_hash=!old_hash: =!
	echo hash^(%old_rtconfig%^)=!old_hash!
)

if !new_hash! neq !old_hash! (
	copy %new_rt_config% %old_rtconfig% /Y
)

"%RTT_EXEC_PATH%\arm-none-eabi-gcc" -E -x c -P %new_linkscript% -o link.lds
"%RTT_EXEC_PATH%\arm-none-eabi-gcc" -E -x c -P ./beken378/func/user_driver/BkFlashPartition.h -o ./tools/beken_packager/flash_partition.o -I ./config
::copy %new_linkscript% link.lds /Y

echo "  %GREEN%GEN  .config%NC%"
echo #include "config/sys_config.h" > config.c
tools\\gnuwin32\\sed.exe -n "/^#define/p" config/sys_config.h | tools\\gnuwin32\\awk.exe "{print $2}" | sort.exe | tools\\gnuwin32\\uniq.exe | tools\\gnuwin32\\awk.exe "{print """valueOf_"""$1"""="""$1}" >> config.c
echo # Autogenerated by Makefile, DON'T EDIT > .config
"%RTT_EXEC_PATH%\arm-none-eabi-gcc" -E config.c -o config_pp.i
tools\\gnuwin32\\grep.exe "^valueOf_" config_pp.i | tools\\gnuwin32\\sed.exe "s/valueOf_//" >> .config
if exist config_pp.i del /f config_pp.i
tools\\gnuwin32\\sed.exe -i "/_SYS_CONFIG_H_/d" .config
if exist config.c del /f config.c

endlocal
