from building import *

cwd  = GetCurrentDir()
src  = Glob('*.c')
# Explicitly add ai_printer.c to ensure it's included on all platforms
if 'ai_printer.c' not in [os.path.basename(f) for f in src]:
    src += [os.path.join(cwd, 'ai_printer.c')]
src += [cwd + '/../beken378/func/base64/base_64.c']
list = os.listdir(cwd)
CPPPATH = [cwd,
           cwd + '/../packages/cJSON',
           cwd + '/../packages/webclient/inc',
           cwd + '/../packages/librws-v1.2.4/include',
           cwd + '/../packages/webnet/inc',
           cwd + '/../packages/EasyFlash/inc',
           cwd + '/../packages/EasyFlash/port',
           cwd + '/../beken378/func/base64']
objs = []

if GetDepend('RT_USING_DFS_ROMFS') == False:
    SrcRemove(src, 'romfs.c')

group = DefineGroup('Application', src, depend = [''], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group
Return('objs')
