#! /bin/sh

LIB_FILES=" \
${BEKEN_SDK_DIR}/driver/bt/Common/driver/driver_audio.c \
${BEKEN_SDK_DIR}/driver/bt/Common/system/BK_HCI_Protocol.c \
${BEKEN_SDK_DIR}/driver/bt/Common/system/bt_sys_comp.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/core/bt_config.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/core/bt_security.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/core/bt_unit.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/core/hci_event.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/core/hci_link.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/core/hci_misc.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/core/hci_security.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/core/hci_unit.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/core/l2cap_lower.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/core/l2cap_misc.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/core/l2cap_signal.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/core/l2cap_upper.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/core/sco_lower.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/core/sco_upper.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/hci/bt_uart.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/profile/a2dp/bt_a2dp_dev.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/profile/a2dp/bt_a2dp_sdp_server.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/profile/a2dp/Bt_a2dp_src_dev.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/profile/a2dp/bt_sbc.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/profile/avrcp/bt_avrcp_dev.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/profile/avrcp/bt_avrcp_sdp_server.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/profile/hfp/bt_hfp.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/profile/hfp/bt_hf_sdp_server.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/profile/hid/bt_hid.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/profile/hid/bt_hid_sdp_server.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/profile/hsp/bt_hsp.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/profile/hsp/bt_hsp_sdp_server.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/profile/sdp/bgd.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/profile/sdp/sd.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/profile/spp/bt_spp.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/profile/spp/bt_spp_sdp_server.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/protocol/avctp/avctp_lower.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/protocol/avctp/avctp_upper.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/protocol/avdtp/avdtp_session.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/protocol/avdtp/avdtp_signal.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/protocol/avdtp/avdtp_upper.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/protocol/rfcomm/rfcomm_dlc.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/protocol/rfcomm/rfcomm_session.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/protocol/rfcomm/rfcomm_upper.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/protocol/sdp/sdp_utils.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/service/bt_devmgr.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/service/bt_init.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/service/sar.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/service/sdp_profile.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/service/sdp_provider.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/service/sdp_server.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/service/sdp_service.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/service/ssar.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/service/ssr.c \
${BEKEN_SDK_DIR}/driver/bt/host/bluetooth/service/uuid.c \
${BEKEN_SDK_DIR}/driver/bt/host/jos/jinit.c \
${BEKEN_SDK_DIR}/driver/bt/host/jos/jos_bus.c \
${BEKEN_SDK_DIR}/driver/bt/host/jos/jos_device.c \
${BEKEN_SDK_DIR}/driver/bt/host/jos/jos_driver.c \
${BEKEN_SDK_DIR}/driver/bt/host/jos/jos_entry.c \
${BEKEN_SDK_DIR}/driver/bt/host/jos/jos_event.c \
${BEKEN_SDK_DIR}/driver/bt/host/jos/jos_general.c \
${BEKEN_SDK_DIR}/driver/bt/host/jos/jos_mbuf.c \
${BEKEN_SDK_DIR}/driver/bt/host/jos/jos_mem.c \
${BEKEN_SDK_DIR}/driver/bt/host/jos/jos_sync.c \
${BEKEN_SDK_DIR}/driver/bt/host/jos/utils/jos_secure_ptr.c \
${BEKEN_SDK_DIR}/driver/bt/host/pkg/sbc/sbc.c \
${BEKEN_SDK_DIR}/driver/bt/host/pkg/sbc/sbc_primitives.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_app/app_bt.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_app/app_env.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_app/app_fat.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_app/app_hfp.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_app/app_msg.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_app/app_prompt_wav.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_app/app_protocol.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_app/app_sbc.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_driver/bt_main.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_driver/target.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_no_os/bus.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_no_os/entry.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_no_os/mem.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_no_os/msg.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_no_os/pts/pts.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_no_os/pts/pts_a2dp.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_no_os/pts/pts_hfp.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_no_os/timer.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_no_os/uart.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/common/app_init.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/common/uw_args.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/common/str_utils.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/common/audio_out_interface/audio_out_none.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/common/bluetooth/bt_a2dp_backend.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/common/bluetooth/Bt_a2dp_src_backend.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/common/bluetooth/bt_app.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/common/bluetooth/bt_avrcp_backend.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/common/bluetooth/bt_cli_frontend.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/common/bluetooth/bt_hf_backend.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/common/bluetooth/bt_hid_backend.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/common/bluetooth/bt_hs_backend.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/common/bluetooth/bt_unit_backend.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/common/bluetooth/bt_sco_backend_utils.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/common/bluetooth/bt_spp_backend.c \
${BEKEN_SDK_DIR}/driver/bt/host/port/beken_app/app_player.c \
${BEKEN_SDK_DIR}/driver/bt/host/libs"
