from building import *

cwd  = GetCurrentDir()
src  = Glob('*.c')
list = os.listdir(cwd)
CPPPATH = [cwd]
objs = []

if GetDepend('BEKEN_USING_FLASH') == False:
    SrcRemove(src, 'drv_flash.c')
    SrcRemove(src, 'drv_flash_disk.c')

if GetDepend('RT_USING_ADC') == False:
    SrcRemove(src, 'drv_adc.c')

if GetDepend('BEKEN_USING_ST7789_LCD') == False:
    SrcRemove(src, 'drv_st7789_lcd.c')

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group
Return('objs')
