from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd]

# Disable pthreads on macOS due to newlib pthread type conflicts with newer GCC
import sys
if sys.platform == 'darwin':
    # Return empty group to skip building pthreads
    group = []
else:
    group = DefineGroup('pthreads', src,
        depend = ['RT_USING_PTHREADS', 'RT_USING_LIBC'], CPPPATH = CPPPATH)

Return('group')
